import {
  Activity,
  Blocks,
  BookOpen,
  Bot,
  BrainCircuit,
  CalendarClock,
  FileText,
  Globe,
  Inbox,
  KeyRound,
  LayoutDashboard,
  MessageCircle,
  LibraryBig,
  Plug,
  ScrollText,
  Send,
  Settings,
  UserRound,
  Users,
  Workflow,
} from "lucide-react";

export const workspacePages = [
  { href: "/", title: "Overview", description: "Visitor activity and important items", group: "Workspace", icon: LayoutDashboard },
  { href: "/conversations", title: "Conversations", description: "Visitor threads, approvals, and replies", group: "Workspace", icon: Inbox },
  { href: "/contacts", title: "Contacts", description: "People, identities, and conversation context", group: "Workspace", icon: Users },
  { href: "/concierge", title: "Agent profile", description: "How your concierge introduces itself and helps people", group: "Your concierge", icon: Bot },
  { href: "/concierge/collections", title: "Collections", description: "Organized information your concierge can share with visitors", group: "Your concierge", icon: LibraryBig },
  { href: "/profile", title: "User profile", description: "Information your concierge should know about you", group: "Your concierge", icon: UserRound },
  { href: "/connections", title: "Connections", description: "Visitor channels, apps, and tools", group: "Build & manage", icon: Plug },
  { href: "/skills", title: "Skills", description: "What your concierge knows how to do", group: "Build & manage", icon: Workflow },
  { href: "/scheduler", title: "Automations", description: "Scheduled and recurring work", group: "Build & manage", icon: CalendarClock, feature: "scheduler" },
  { href: "/settings", title: "Settings", description: "AI service and workspace preferences", group: "Build & manage", icon: Settings },
  { href: "/llms", title: "AI service", description: "Choose and configure the AI that powers Youbot", group: "Settings", icon: BrainCircuit },
  { href: "/integrations", title: "Apps & tools", description: "Connect calendars, files, and other services", group: "Connections", icon: Blocks },
  { href: "/mcp-servers", title: "Custom tool servers", description: "Connect external tools through MCP", group: "Connections", icon: Plug, feature: "mcp" },
  { href: "/whatsapp", title: "WhatsApp", description: "Account connection and automatic replies", group: "Connections", icon: MessageCircle, feature: "whatsapp" },
  { href: "/telegram", title: "Telegram", description: "Bot connection and automatic replies", group: "Connections", icon: Send, feature: "telegram" },
  { href: "/webchat", title: "Website chat", description: "Visitor widget and website connection", group: "Connections", icon: Globe, feature: "webchat" },
  { href: "/profile", title: "User profile", description: "Owner details and context", group: "Settings", icon: UserRound },
  { href: "/personas", title: "Profile documents", description: "Additional instructions and reference material", group: "Settings", icon: FileText },
  { href: "/vault", title: "Secure storage", description: "Saved credentials and protected documents", group: "Settings", icon: KeyRound },
  { href: "/tools", title: "System status", description: "Availability of tools and services", group: "Advanced", icon: Activity },
  { href: "/logs", title: "Activity logs", description: "Detailed events and diagnostic information", group: "Advanced", icon: ScrollText },
  { href: "/setup", title: "Setup guide", description: "Complete or review the guided setup", group: "Support", icon: BookOpen },
  { href: "/help", title: "Help", description: "Installation and common questions", group: "Support", icon: BookOpen },
];
