"use client";
import { useEffect,useMemo,useRef,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Send, Inbox, ArrowRight, Check, UserRound } from 'lucide-react';
import { ListToolbar } from '@/components/list-toolbar';
import { WorkspacePage } from '@/components/workspace-frame';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { conciergeApi,channelName,statusName,time,type Thread,type Detail,type Message } from '@/lib/concierge';
export default function Conversations(){
 const [threads,setThreads]=useState<Thread[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[channel,setChannel]=useState('all'),[sort,setSort]=useState('recent');
 const [selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[threadError,setThreadError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState(''),[notice,setNotice]=useState(''),[decision,setDecision]=useState<Record<string,string>>({});
 const selectedRef=useRef(''),listRequest=useRef(0),detailRequest=useRef(0),pending=useRef<{id:string;content:string;requestId:string}|null>(null);
 async function loadList(){const seq=++listRequest.current;try{const data=await conciergeApi<{threads:Thread[];total:number}>('/threads?'+new URLSearchParams({search,filter,channel,offset:String(offset)}));if(seq!==listRequest.current)return;setThreads(data.threads);setTotal(data.total);setError('');}catch(e){if(seq===listRequest.current)setError((e as Error).message);}finally{if(seq===listRequest.current)setLoading(false);}}
 async function loadDetail(id:string){const seq=++detailRequest.current;try{const data=await conciergeApi<Detail>('/threads/'+encodeURIComponent(id));if(selectedRef.current!==id||seq!==detailRequest.current)return;setDetail(old=>old?.thread.id===id&&old.messages.length>200?{...data,messages:[...old.messages.filter(m=>!data.messages.some(n=>n.id===m.id)),...data.messages],hasMore:old.hasMore}:data);setThreadError('');await conciergeApi('/threads/'+encodeURIComponent(id)+'/read',{version:data.thread.incomingVersion});if(selectedRef.current===id)setThreads(old=>old.map(t=>t.id===id&&t.incomingVersion<=data.thread.incomingVersion?{...t,unread:false}:t));}catch(e){if(selectedRef.current===id&&seq===detailRequest.current)setThreadError((e as Error).message);}}
 function select(id:string){selectedRef.current=id;setSelected(id);setDetail(null);setThreadError('');setNotice('');pending.current=null;setDraft(sessionStorage.getItem('youbot-draft:'+id)||'');const url=new URL(window.location.href);id?url.searchParams.set('thread',id):url.searchParams.delete('thread');window.history.replaceState(null,'',url);}
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const f=p.get('filter');if(f&&['unread','needs','handled'].includes(f))setFilter(f);if(p.get('thread'))select(p.get('thread')!);return()=>{selectedRef.current='';++listRequest.current;++detailRequest.current;};},[]);
 useEffect(()=>{const timeout=setTimeout(()=>void loadList(),200);const timer=setInterval(()=>void loadList(),10000);return()=>{clearTimeout(timeout);clearInterval(timer);++listRequest.current;};},[search,filter,channel,offset]);
 useEffect(()=>{if(!selected)return;void loadDetail(selected);const timer=setInterval(()=>void loadDetail(selected),8000);return()=>clearInterval(timer);},[selected]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(draft.trim()){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[draft]);
 function changeDraft(value:string){setDraft(value);sessionStorage.setItem('youbot-draft:'+selected,value);pending.current=null;}
 async function action(endpoint:string,body:unknown){if(!detail||busy)return;const id=selected;setBusy(true);setThreadError('');try{await conciergeApi('/threads/'+encodeURIComponent(id)+'/'+endpoint,body);await loadDetail(id);await loadList();}catch(e){if(selectedRef.current===id)setThreadError((e as Error).message);}finally{setBusy(false);}}
 async function send(){if(!detail||!draft.trim()||busy)return;const id=selected,content=draft.trim();pending.current ||= {id,content,requestId:crypto.randomUUID()};setBusy(true);setThreadError('');try{const result=await conciergeApi<{message:Message}>('/threads/'+encodeURIComponent(id)+'/reply',{content,requestId:pending.current.requestId,channel:detail.thread.channel,version:detail.thread.incomingVersion});if(result.message.delivery!=='sent')throw new Error('This reply has an unknown delivery status. Check the messaging app before sending it again.');sessionStorage.removeItem('youbot-draft:'+id);if(selectedRef.current===id){setDraft('');pending.current=null;setNotice('Reply sent.');}await loadDetail(id);await loadList();}catch(e){if(selectedRef.current===id)setThreadError((e as Error).message);}finally{setBusy(false);}}
 async function older(){if(!detail||busy)return;const id=selected;setBusy(true);try{const data=await conciergeApi<Detail>('/threads/'+encodeURIComponent(id)+'?before='+encodeURIComponent(detail.messages[0].id));if(selectedRef.current===id)setDetail(old=>old?{...old,messages:[...data.messages,...old.messages.filter(m=>!data.messages.some(n=>n.id===m.id))],hasMore:data.hasMore}:old);}catch(e){setThreadError((e as Error).message);}finally{setBusy(false);}}
 const t=detail?.thread;
 const visibleThreads=useMemo(()=>[...threads].sort((left,right)=>{
   if(sort==='name')return left.name.localeCompare(right.name,undefined,{sensitivity:'base'});
   const difference=Date.parse(right.updatedAt)-Date.parse(left.updatedAt);
   return sort==='oldest'?-difference:difference;
 }),[threads,sort]);
 return <WorkspacePage className="signature-inbox" title="Conversations" description="Every visitor. Every exchange. All in one place."><div className="correspondence-desk flex min-h-0 flex-1 overflow-hidden bg-card">
 <section aria-label="Conversation list" className={`${selected?'hidden lg:flex':'flex'} w-full flex-col border-r lg:w-80 lg:shrink-0 xl:w-96`}><ListToolbar searchLabel="Search conversations" searchPlaceholder="Search conversations" searchValue={search} onSearchChange={value=>{setSearch(value);setOffset(0);}} filters={[{label:'Conversation status',value:filter,onValueChange:value=>{setFilter(value);setOffset(0);},options:[{value:'all',label:'All statuses'},{value:'needs',label:'Requires attention'},{value:'unread',label:'Unread'},{value:'handled',label:'Resolved'}]},{label:'Messaging app',value:channel,onValueChange:value=>{setChannel(value);setOffset(0);},options:[{value:'all',label:'All messaging apps'},{value:'whatsapp',label:'WhatsApp'},{value:'telegram',label:'Telegram'},{value:'webchat',label:'Website'}]}]} sort={{label:'Sort conversations',value:sort,onValueChange:setSort,options:[{value:'recent',label:'Newest first'},{value:'oldest',label:'Oldest first'},{value:'name',label:'Name A–Z'}]}} resultLabel={`${total} conversation${total===1?'':'s'}`} active={!!search||filter!=='all'||channel!=='all'||sort!=='recent'} onReset={()=>{setSearch('');setFilter('all');setChannel('all');setSort('recent');setOffset(0);}}/>
 {error&&<div role="alert" className="p-4 text-sm">{error}<Button variant="outline" className="mt-2" onClick={()=>void loadList()}>Try again</Button></div>}
 <div className="max-h-[75vh] flex-1 overflow-y-auto">{loading?<p role="status" className="p-5 text-sm">Loading conversations…</p>:!visibleThreads.length?<div className="space-y-3 p-6 text-sm"><Inbox className="size-7 text-muted-foreground"/><h2 className="font-medium">{search||filter!=='all'||channel!=='all'?'No matching conversations':'No conversations yet'}</h2><p className="text-muted-foreground">{search||filter!=='all'||channel!=='all'?'Try another search or filter.':'Once someone messages your concierge, their conversation appears here.'}</p><Link className="underline underline-offset-4" href="/connections">Manage connections</Link></div>:visibleThreads.map(thread=><button disabled={busy} onClick={()=>select(thread.id)} key={thread.id} aria-current={selected===thread.id?'true':undefined} className={`block w-full space-y-2 border-b p-4 text-left transition-colors hover:bg-muted/50 ${selected===thread.id?'bg-primary/5 border-l-2 border-l-primary':''}`}><span className="flex items-center gap-2"><span className="correspondent-mark" aria-hidden="true">{thread.name.charAt(0).toUpperCase()}</span><span className={`flex-1 truncate text-sm ${thread.unread?'font-semibold':'font-medium'}`}>{thread.name}</span>{thread.unread&&<span aria-label="Unread" className="size-2 rounded-full bg-primary"/>}<span className="text-[11px] text-muted-foreground">{channelName(thread.channel)}</span></span><span className="block truncate text-sm text-muted-foreground">{thread.preview||'Attachment'}</span><span className="flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{statusName(thread)}</span><span>{time(thread.updatedAt)}</span></span></button>)}</div>
 {total>50&&<div className="flex items-center justify-between border-t p-3 text-xs"><Button size="sm" variant="ghost" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</Button><span>{offset+1}–{Math.min(offset+50,total)} of {total}</span><Button size="sm" variant="ghost" disabled={offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</Button></div>}</section>
 <section aria-label="Visitor conversation" className={`${selected?'flex':'hidden lg:flex'} min-w-0 flex-1 flex-col`}>
 {!selected?<div className="m-auto max-w-xs space-y-3 p-6 text-center"><Inbox className="mx-auto size-8 text-muted-foreground"/><h2 className="font-medium">Select a conversation</h2><p className="text-sm text-muted-foreground">Review the complete message history and manage responses.</p></div>:<>
 <div className="flex flex-wrap items-center gap-3 border-b p-4"><Button size="icon" variant="ghost" disabled={busy} onClick={()=>select('')} className="lg:hidden" aria-label="Back to conversations"><ArrowLeft className="size-4"/></Button><div className="min-w-32 flex-1"><h2 className="truncate font-semibold">{t?.name||'Loading conversation…'}</h2>{t&&<p className="text-xs text-muted-foreground">{channelName(t.channel)} · {t.paused?'Manual response mode':detail?.autoReplyEnabled?'Concierge replies are on':'Automatic replies are off'}</p>}</div>{t&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void action('control',{action:t.handled?'reopen':'handled',version:t.incomingVersion})}><Check className="size-4"/>{t.handled?'Reopen':'Mark resolved'}</Button>}</div>
 {threadError&&<div role="alert" className="space-y-2 border-b bg-destructive/5 p-4 text-sm"><p>{threadError}</p><Button variant="outline" size="sm" onClick={()=>void loadDetail(selected)}>Refresh conversation</Button></div>}
 {detail&&t?<><div className="max-h-[65vh] min-h-60 flex-1 space-y-4 overflow-y-auto p-4 sm:p-6">
 {(t.lastError||detail.approvals.length>0||detail.followups.length>0)&&<aside aria-label="Items needing your attention" className="space-y-3 rounded-xl border bg-muted/30 p-4"><h3 className="text-sm font-semibold">Pending items</h3>{t.lastError&&<div className="space-y-2 text-sm"><p>{t.lastError}</p><p className="text-xs text-muted-foreground">Check the original messaging app. Acknowledging keeps the reply’s delivery record unchanged.</p><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action('resolve',{kind:'error',error:t.lastError})}>I’ve checked this</Button></div>}{detail.approvals.map(a=><div key={a.id} className="space-y-2 border-t pt-3"><p className="text-sm font-medium">{a.question}</p><p className="text-xs text-muted-foreground">{a.context}</p><Input aria-label={'Decision for '+a.question} placeholder="Add your decision or what you did" value={decision[a.id]||''} onChange={e=>setDecision({...decision,[a.id]:e.target.value})}/><Button size="sm" variant="outline" disabled={busy||!decision[a.id]?.trim()} onClick={()=>void action('resolve',{kind:'approval',id:a.id,note:decision[a.id]})}>Save decision</Button><p className="text-xs text-muted-foreground">Saved for your concierge. To message the visitor now, take over and reply below.</p></div>)}{detail.followups.map(f=><div key={f.id} className="flex flex-wrap items-center justify-between gap-2 border-t pt-3 text-sm"><span>{f.reason}<span className="block text-xs text-muted-foreground">Due {time(f.follow_up_at)}</span></span><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action('resolve',{kind:'followup',id:f.id})}>Mark done</Button></div>)}</aside>}
 <details className="rounded-lg border px-4 py-3 text-sm"><summary className="cursor-pointer font-medium">Visitor details</summary><dl className="mt-3 grid gap-2 text-xs text-muted-foreground"><div><dt className="inline font-medium">Messaging app: </dt><dd className="inline">{channelName(t.channel)}</dd></div><div><dt className="inline font-medium">First seen: </dt><dd className="inline">{time(t.createdAt)}</dd></div><div><dt className="inline font-medium">Last message: </dt><dd className="inline">{time(t.lastIncomingAt)}</dd></div></dl></details>
 {detail.hasMore&&<Button className="mx-auto flex" size="sm" variant="outline" disabled={busy} onClick={()=>void older()}>Load earlier messages</Button>}
 {!detail.messages.length&&<p className="text-sm text-muted-foreground">No messages in this conversation yet.</p>}
 {detail.messages.map(m=><article key={m.id} className={`max-w-[92%] rounded-xl border p-4 sm:max-w-[85%] ${m.speaker==='visitor'?'bg-background':'ml-auto bg-muted/40'}`}><div className="mb-2 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span className="font-medium text-foreground">{m.speaker==='visitor'?t.name:m.speaker==='owner'?'You':'Concierge'}</span><time dateTime={m.timestamp}>{time(m.timestamp)}</time></div><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{m.content||'Attachment — open the messaging app to view it.'}</p>{m.speaker!=='visitor'&&<p className={`mt-2 text-xs ${m.delivery==='unknown'?'text-destructive':'text-muted-foreground'}`}>{m.delivery==='historical'?'Earlier reply · delivery not recorded':m.delivery==='sent'?'Sent':m.delivery==='unknown'?'Delivery unknown':m.delivery==='sending'?'Sending…':m.delivery}</p>}</article>)}
 </div><footer className="space-y-3 border-t p-4">{t.paused?<><div className="flex flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2 text-sm font-medium"><UserRound className="size-4"/>Manual response mode</span><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void action('control',{action:'handback',version:t.incomingVersion})}>Resume automatic replies <ArrowRight className="size-4"/></Button></div><p className="text-xs text-muted-foreground">Automatic replies are paused for this visitor.</p></>:<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{detail.autoReplyEnabled?"Automatic replies are enabled for this conversation.":"Automatic replies are off for this app. You can still take over and reply."}</p><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action('control',{action:'takeover',version:t.incomingVersion})}>Respond manually</Button></div>}
 {(t.paused||draft)&&<><Textarea aria-label="Reply to visitor" value={draft} maxLength={10000} disabled={busy} onChange={e=>changeDraft(e.target.value)} placeholder="Write your reply…" className="min-h-24"/><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{draft?'Draft saved in this browser tab.':'Replies go to '+channelName(t.channel)+'.'}</span><Button disabled={busy||!t.paused||!draft.trim()||!!detail.replyUnavailable||!!t.lastError} onClick={()=>void send()}><Send className="size-4"/>{busy?'Working…':'Send reply'}</Button></div></>}
 {detail.replyUnavailable&&<p className="text-xs text-muted-foreground">{detail.replyUnavailable} <Link href="/connections" className="underline">Connections</Link></p>}{notice&&<p role="status" className="text-xs text-muted-foreground">{notice}</p>}
 </footer></>:!threadError&&<p role="status" className="p-6 text-sm">Loading the conversation…</p>}</>}
 </section></div></WorkspacePage>;
}
