"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,ArrowRight,Check,Plus,Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { ListToolbar } from '@/components/list-toolbar';
import { WorkspacePage } from '@/components/workspace-frame';
import { conciergeApi,type Profile } from '@/lib/concierge';
const steps=['Identity','Responsibilities','Communication','Knowledge','Response policies','Connections'];
export default function Concierge(){
 const [profile,setProfile]=useState<Profile|null>(null),[revision,setRevision]=useState(0),[step,setStep]=useState(0),[sectionSearch,setSectionSearch]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{const data=await conciergeApi<{profile:Profile;revision:number}>('/profile');const savedDraft=sessionStorage.getItem('youbot-concierge-draft');
 let restored=false;
 if(savedDraft){try{const draft=JSON.parse(savedDraft);if(draft.profile&&typeof draft.revision==='number'){setProfile(draft.profile);setRevision(draft.revision);setDirty(true);setNotice('Unsaved profile changes restored.');restored=true;}}catch{sessionStorage.removeItem('youbot-concierge-draft');}}
 if(!restored){setProfile(data.profile);setRevision(data.revision);setDirty(false);}setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{if(profile&&dirty)sessionStorage.setItem('youbot-concierge-draft',JSON.stringify({profile,revision}));},[profile,revision,dirty]);
 function update(value:Partial<Profile>){setProfile(p=>p?{...p,...value}:p);setDirty(true);setNotice('');}
 async function save(){if(!profile||saving)return;setSaving(true);setError('');try{const saved=await conciergeApi<{profile:Profile;revision:number}>('/profile',{profile,revision},'PUT');setProfile(saved.profile);setRevision(saved.revision);setDirty(false);sessionStorage.removeItem('youbot-concierge-draft');setNotice('Saved. Your concierge will use this for new replies.');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 const field=(label:string,key:'name'|'introduction'|'purpose',hint:string,max:number,multiline=false)=><label className="block space-y-2"><span className="text-sm font-medium">{label}</span>{multiline?<Textarea disabled={saving} value={profile![key]} maxLength={max} onChange={e=>update({[key]:e.target.value})} className="min-h-32"/>:<Input disabled={saving} value={profile![key]} maxLength={max} onChange={e=>update({[key]:e.target.value})}/>}<span className="block text-xs leading-relaxed text-muted-foreground">{hint}</span></label>;
 const visibleSteps=steps.map((label,index)=>({label,index})).filter(({label})=>label.toLowerCase().includes(sectionSearch.trim().toLowerCase()));
 return <WorkspacePage className="signature-agent" title="Agent profile" description="Define how your concierge represents you, what it knows and when it should request approval." actions={<Button disabled={!profile||saving||(!dirty&&revision>0)} onClick={()=>void save()}><Check className="size-4"/>{saving?'Saving…':'Save changes'}</Button>}>{error&&<div role="alert" className="workspace-page-feedback space-y-3 rounded-xl border p-4"><p>{error}</p>{!profile&&<Button variant="outline" onClick={()=>void load()}>Try again</Button>}{profile&&error.includes('another window')&&<Button variant="outline" onClick={()=>{if(window.confirm('Reload the saved concierge and discard these unsaved changes?')){sessionStorage.removeItem('youbot-concierge-draft');void load();}}}>Reload saved version</Button>}</div>}{notice&&<p role="status" className="workspace-page-feedback rounded-lg bg-primary/5 p-3 text-sm">{notice}</p>}
 {!profile&&!error?<p role="status" className="p-5">Loading your concierge…</p>:profile&&<div className="workspace-columns"><nav aria-label="Agent profile sections" className="agent-index workspace-rail hidden flex-col lg:flex"><ListToolbar searchLabel="Search agent profile sections" searchPlaceholder="Search sections" searchValue={sectionSearch} onSearchChange={setSectionSearch} resultLabel={`${visibleSteps.length} of ${steps.length} sections`} active={!!sectionSearch} onReset={()=>setSectionSearch('')}/><div className="agent-section-list flex flex-col gap-1 p-3">{visibleSteps.length===0?<p className="p-3 text-sm text-muted-foreground">No matching sections.</p>:visibleSteps.map(({label,index})=><button key={label} onClick={()=>setStep(index)} aria-current={step===index?'step':undefined} className={`flex shrink-0 items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${step===index?'bg-primary/10 font-medium':'text-muted-foreground hover:bg-muted'}`}><span className="flex size-6 shrink-0 items-center justify-center rounded-full border text-xs">{index+1}</span>{label}</button>)}</div></nav><section className="agent-document workspace-canvas min-w-0 p-5 sm:p-7"><label className="mb-5 block space-y-2 lg:hidden"><span className="text-xs font-medium text-muted-foreground">Agent profile section</span><select aria-label="Agent profile section" className="h-11 w-full rounded-lg border bg-card px-3 text-sm" value={step} onChange={event=>setStep(Number(event.target.value))}>{steps.map((label,index)=><option key={label} value={index}>{label}</option>)}</select></label><p className="text-xs text-muted-foreground">Profile configuration · {step+1} / 6</p><h2 className="mb-6 mt-2 text-xl font-semibold">{steps[step]}</h2><div className="space-y-6">
 {step===0&&<>{field('Agent name','name','The name used when introducing your concierge to visitors.',60)}{field('Introduction','introduction','A brief introduction that explains whom your agent represents and how it can help.',500,true)}<div className="agent-introduction"><p className="signature-eyebrow">Visitor introduction</p><p className="agent-preview-name">{profile.name||'Your concierge'}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{profile.introduction||'Add an introduction to preview it here.'}</p></div></>}
 {step===1&&<>{field('Role & responsibilities','purpose','Describe the requests it should handle, information it should collect and decisions requiring your approval.',3000,true)}<div className="space-y-2"><p className="text-sm font-medium">Suggested responsibilities</p>{['Help people learn about my work and collect enquiries. Ask me before making any promises.','Welcome visitors, answer questions from my notes, and collect the details I need to help them.','Help my community find the right information. Pass questions I need to answer back to me.'].map(text=><button disabled={saving} key={text} onClick={()=>update({purpose:text})} className="block w-full rounded-lg border p-3 text-left text-sm hover:bg-muted">{text}</button>)}</div></>}
 {step===2&&<fieldset disabled={saving} className="space-y-3"><legend className="mb-3 text-sm text-muted-foreground">Choose a consistent communication style for visitor conversations.</legend>{([['warm','Approachable','Welcoming, clear and considerate.'],['direct','Concise','Direct responses with essential detail.'],['polished','Professional','Measured, precise and courteous.']] as const).map(([value,title,desc])=><label key={value} className={`flex cursor-pointer gap-3 rounded-xl border p-4 ${profile.tone===value?'border-primary bg-primary/5':''}`}><input type="radio" name="tone" checked={profile.tone===value} onChange={()=>update({tone:value})} className="mt-1"/><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-sm text-muted-foreground">{desc}</span></span></label>)}</fieldset>}
 {step===3&&<><p className="text-sm text-muted-foreground">Provide reference information such as services, availability, pricing and frequently asked questions.</p>{profile.knowledge.map((note,i)=><div key={note.id} className="space-y-3 rounded-xl border p-4"><div className="flex gap-2"><Input aria-label={`Note ${i+1} title`} placeholder="Title, for example Business hours" value={note.title} disabled={saving} maxLength={120} onChange={e=>update({knowledge:profile.knowledge.map(n=>n.id===note.id?{...n,title:e.target.value}:n)})}/><Button disabled={saving} variant="ghost" size="icon" aria-label={`Remove note ${i+1}`} onClick={()=>update({knowledge:profile.knowledge.filter(n=>n.id!==note.id)})}><Trash2 className="size-4"/></Button></div><Textarea aria-label={`Note ${i+1} content`} placeholder="Enter the reference information." value={note.content} disabled={saving} maxLength={5000} onChange={e=>update({knowledge:profile.knowledge.map(n=>n.id===note.id?{...n,content:e.target.value}:n)})}/></div>)}<Button variant="outline" disabled={saving||profile.knowledge.length>=30} onClick={()=>update({knowledge:[...profile.knowledge,{id:crypto.randomUUID(),title:'',content:''}]})}><Plus className="size-4"/>Add a note</Button><p className="text-xs text-muted-foreground">Up to 30 reference notes. Store credentials in Secure storage rather than profile notes.</p></>}
 {step===4&&<><p className="text-sm text-muted-foreground">Set response policies and approval requirements. Tool permissions continue to apply independently.</p>{([['answerFromKnowledge','Answer from reference notes','Acknowledge missing information rather than inventing an answer.'],['askBeforePrice','Require approval for pricing','Request approval before agreeing to prices, discounts or payment commitments.'],['askBeforeBooking','Require approval for bookings','Collect the required details and request approval before confirming.']] as const).map(([key,title,hint])=><label key={key} className="flex gap-3 rounded-xl border p-4"><input type="checkbox" disabled={saving} checked={profile.boundaries[key]} onChange={e=>update({boundaries:{...profile.boundaries,[key]:e.target.checked}})} className="mt-1"/><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{hint}</span></span></label>)}<label className="block space-y-2"><span className="text-sm font-medium">Approval request message</span><Textarea disabled={saving} value={profile.boundaries.escalation} maxLength={500} onChange={e=>update({boundaries:{...profile.boundaries,escalation:e.target.value}})}/></label><Link href="/safety" className="inline-block text-sm underline underline-offset-4">Manage tool permissions</Link></>}
 {step===5&&<><div className="rounded-xl bg-muted/40 p-5"><h3 className="font-medium">{profile.name} · Configuration summary</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm text-muted-foreground">{profile.purpose||'Define the agent’s responsibilities before connecting visitor channels.'}</p><p className="mt-3 text-xs text-muted-foreground">{profile.knowledge.length} knowledge notes · {profile.tone} voice</p></div><p className="text-sm text-muted-foreground">Save your profile, configure an AI provider and connect the channels visitors will use. Incoming messages appear in Conversations.</p><div className="divide-y rounded-xl border">{[['/setup','AI provider','Configure your preferred AI service or local model.'],['/connections','Messaging channels','Manage visitor channels and automatic replies.'],['/conversations','Conversation inbox','Review visitor threads and respond when required.']].map(([href,title,hint])=><Link key={href} href={href} className="flex items-center justify-between gap-3 p-4 hover:bg-muted/40"><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{hint}</span></span><ArrowRight className="size-4 shrink-0"/></Link>)}</div><p className="text-xs text-muted-foreground">Self-hosted availability depends on Youbot running and the host computer remaining awake.</p></>}
 <Link href="/personas?profile=agent" className="inline-block text-xs font-medium text-primary underline-offset-4 hover:underline">Manage additional agent instructions</Link></div><footer className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft className="size-4"/>Back</Button><p className="text-xs text-muted-foreground">{dirty?'Unsaved changes':revision?'Changes saved':'Profile not yet saved'}</p>{step<5?<Button onClick={()=>setStep(step+1)}>Next <ArrowRight className="size-4"/></Button>:<Button disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save profile'}<Check className="size-4"/></Button>}</footer></section></div>}</WorkspacePage>;
}
