'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import {FileText,Eye,Save,ArrowUpRight} from 'lucide-react';
import {FormFeedback} from '@/components/page-header';
import {StandardPage} from '@/components/workspace-frame';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {api} from '@/lib/api';
interface Document {content:string;revision:string}
export default function ProfileDocuments(){
 const [selected,setSelected]=useState('__bot__'),[data,setData]=useState<Document|null>(null),[content,setContent]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[preview,setPreview]=useState(false),[reload,setReload]=useState(0);
 const dirty=!!data&&content!==data.content;
 useEffect(()=>{if(new URLSearchParams(location.search).get('profile')==='owner')setSelected('__owner__');},[]);
 useEffect(()=>{let active=true;setData(null);setError('');api<Document>('/api/personas/'+encodeURIComponent(selected)).then(d=>{if(active){setData(d);setContent(d.content);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,reload]);
 useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
 function select(id:string){if(dirty&&!window.confirm('Discard unsaved document changes?'))return;setSelected(id);setNotice('');}
 async function save(){if(!data||saving)return;setSaving(true);setError('');setNotice('');try{await api('/api/personas/'+encodeURIComponent(selected),{method:'PUT',body:{content,revision:data.revision}});const saved=await api<Document>('/api/personas/'+encodeURIComponent(selected));if(saved.content!==content)throw new Error('The saved document does not match your changes. Reload and review it before trying again.');setData(saved);setNotice('Profile document saved.');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <StandardPage title="Profile documents" description="Review supporting instructions and context used by the concierge. Existing content is preserved." actions={<Button disabled={!dirty||saving} onClick={()=>void save()}><Save className="size-4"/>{saving?'Saving…':'Save document'}</Button>}><div className="flex flex-wrap items-center justify-between gap-3"><nav className="flex rounded-lg border bg-card p-1" aria-label="Profile documents">{[['__bot__','Agent instructions'],['__owner__','Owner context']].map(([id,label])=><button key={id} aria-pressed={selected===id} disabled={saving} onClick={()=>select(id)} className={`rounded-md px-4 py-2 text-sm ${selected===id?'bg-primary/10 font-medium text-primary':'text-muted-foreground'}`}>{label}</button>)}</nav><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?<FileText className="size-4"/>:<Eye className="size-4"/>}{preview?'Edit document':'Preview'}</Button></div><FormFeedback error={error} notice={notice}/>{error&&<Button variant="outline" onClick={()=>{if(!dirty||window.confirm('Reload the saved document and discard unsaved changes?')){setNotice('');setReload(value=>value+1);}}}>Reload saved document</Button>}<div className="rounded-xl border bg-card p-5 text-sm leading-6 text-muted-foreground">{selected==='__bot__'?'Use this document for additional instructions. Manage identity, responsibilities and communication style in Agent profile.':'Owner context is used when the concierge represents you in conversations. Manage structured personal details in User profile.'}<Link href={selected==='__bot__'?'/concierge':'/profile'} className="mt-2 flex items-center gap-1 font-medium text-primary">{selected==='__bot__'?'Open agent profile':'Open user profile'}<ArrowUpRight className="size-3.5"/></Link></div>{!data?!error&&<p role="status">Loading document…</p>:preview?<article className="profile-document min-h-96 rounded-xl border bg-card p-6 text-sm leading-7"><ReactMarkdown>{content||'No additional instructions have been saved.'}</ReactMarkdown></article>:<Textarea aria-label={selected==='__bot__'?'Agent instructions':'Owner context'} value={content} disabled={saving} onChange={e=>setContent(e.target.value)} className="min-h-[440px] bg-card p-5 font-mono text-sm leading-7"/>}<p className="text-xs text-muted-foreground">{dirty?'Unsaved changes':data?'Document matches the saved version':''}</p></StandardPage>;
}
